const PRODUCTS=[
{id:'swift-run',name:'Swift Run Sneakers',category:'sneakers',gender:'men',price:6490,old:7990,rating:4.8,image:'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=700&q=85',tag:'Bestseller',desc:'A lightweight everyday sneaker with a cushioned ride and clean, versatile style.'},
{id:'aero-knit',name:'Aero Knit Runners',category:'sneakers',gender:'women',price:7290,old:null,rating:4.9,image:'https://images.unsplash.com/photo-1552346154-21d32810aba3?auto=format&fit=crop&w=700&q=85',tag:'New',desc:'Breathable knit comfort for busy days and easy movement.'},
{id:'court-classic',name:'Court Classic Low',category:'casual',gender:'men',price:5890,old:6990,rating:4.7,image:'https://images.unsplash.com/photo-1560769629-975ec94e6a86?auto=format&fit=crop&w=700&q=85',tag:'Sale',desc:'A timeless low-top with a crisp finish and all-day comfort.'},
{id:'soleil-sandal',name:'Soleil Comfort Sandals',category:'sandals',gender:'women',price:4290,old:null,rating:4.6,image:'https://images.unsplash.com/photo-1562273138-f46be4ebdf33?auto=format&fit=crop&w=700&q=85',tag:'New',desc:'Easy, sunny-day comfort with a supportive footbed.'},
{id:'urban-formal',name:'Urban Formal Loafers',category:'formal',gender:'men',price:8990,old:null,rating:4.8,image:'https://images.unsplash.com/photo-1614252369475-531eba835eb1?auto=format&fit=crop&w=700&q=85',tag:'',desc:'Polished leather-look loafers for workdays and celebrations.'},
{id:'mini-step',name:'Mini Step Kids Trainers',category:'kids',gender:'kids',price:3990,old:4590,rating:4.7,image:'https://images.unsplash.com/photo-1514989940723-e8e51635b782?auto=format&fit=crop&w=700&q=85',tag:'Sale',desc:'Play-ready trainers designed for growing feet.'},
{id:'cloud-walk',name:'Cloud Walk Slip-ons',category:'casual',gender:'women',price:5490,old:null,rating:4.5,image:'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?auto=format&fit=crop&w=700&q=85',tag:'',desc:'Slip-on simplicity with soft cushioning underfoot.'},
{id:'trail-pro',name:'Trail Pro Outdoor',category:'sports',gender:'men',price:9490,old:null,rating:4.8,image:'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?auto=format&fit=crop&w=700&q=85',tag:'New',desc:'Confident grip and durable comfort for outdoor adventures.'}
];
const money=n=>'Rs. '+n.toLocaleString('en-PK');
const getCart=()=>JSON.parse(localStorage.getItem('smartshoes-cart')||'[]');
function saveCart(c){localStorage.setItem('smartshoes-cart',JSON.stringify(c));updateCount()}
function updateCount(){document.querySelectorAll('.cart-count').forEach(x=>x.textContent=getCart().reduce((s,i)=>s+i.qty,0))}
function card(p){return `<article class="product-card"><a class="product-image" href="product.html?id=${p.id}"><img loading="lazy" src="${p.image}" alt="${p.name}">${p.tag?`<span class="badge">${p.tag}</span>`:''}</a><button class="heart" data-wish="${p.id}" aria-label="Save ${p.name}">♡</button><div class="product-info"><p>★ ${p.rating} · ${p.category}</p><h3><a href="product.html?id=${p.id}">${p.name}</a></h3><span class="price">${money(p.price)} ${p.old?`<del class="old-price">${money(p.old)}</del>`:''}</span></div></article>`}
function renderProducts(list,target){const el=document.querySelector(target);if(el)el.innerHTML=list.map(card).join('')||''}
function add(id,size='8'){const existing=getCart();const found=existing.find(x=>x.id===id&&x.size===size);found?found.qty++:existing.push({id,size,qty:1});saveCart(existing);alert('Added to your cart!')}
function initHome(){renderProducts(PRODUCTS.slice(0,4),'#featured-products')}
function initShop(){const params=new URLSearchParams(location.search),cat=params.get('category');const category=document.querySelector('#category-filter');if(cat&&category)category.value=cat;const run=()=>{let q=document.querySelector('#search-input').value.toLowerCase(), c=category.value, max=+document.querySelector('#price-filter').value;let list=PRODUCTS.filter(p=>(c==='all'||p.category===c||p.gender===c)&&p.price<=max&&(!q||(p.name+' '+p.category+' '+p.gender).toLowerCase().includes(q)));const sort=document.querySelector('#sort-select').value;if(sort==='low')list.sort((a,b)=>a.price-b.price);if(sort==='high')list.sort((a,b)=>b.price-a.price);if(sort==='rating')list.sort((a,b)=>b.rating-a.rating);renderProducts(list,'#shop-products');document.querySelector('#result-count').textContent=`${list.length} pairs to discover`;document.querySelector('#empty-state').hidden=!!list.length};['#search-input','#category-filter','#price-filter','#sort-select'].forEach(s=>document.querySelector(s).addEventListener('input',run));document.querySelector('#clear-filters').onclick=()=>{category.value='all';document.querySelector('#search-input').value='';document.querySelector('#price-filter').value=20000;run()};document.querySelector('#empty-reset').onclick=()=>{document.querySelector('#clear-filters').click()};run()}
function initProduct(){const p=PRODUCTS.find(x=>x.id===new URLSearchParams(location.search).get('id'))||PRODUCTS[0];document.title=p.name+' | SmartShoes';document.querySelector('#product-detail').innerHTML=`<div class="product-detail"><div class="detail-image"><img src="${p.image}" alt="${p.name}"></div><div class="detail-copy"><span class="eyebrow">${p.category.toUpperCase()} · ★ ${p.rating}</span><h1>${p.name}</h1><p>${p.desc}</p><div class="price">${money(p.price)} ${p.old?`<del class="old-price">${money(p.old)}</del>`:''}</div><strong>Choose size</strong><div class="size-options">${[6,7,8,9,10].map(s=>`<button data-size="${s}">${s}</button>`).join('')}</div><button class="btn btn-primary" id="add-product">Add to cart <span>→</span></button></div></div>`;let size='';document.querySelectorAll('[data-size]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-size]').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');size=b.dataset.size});document.querySelector('#add-product').onclick=()=>size?add(p.id,size):alert('Please select a size first.')}
function initCart(){const el=document.querySelector('#cart-content'),cart=getCart();if(!cart.length){el.innerHTML='<div class="empty-state"><h2>Your cart is empty</h2><p>Find a pair you will love.</p><a class="btn btn-primary" href="shop.html">Shop shoes →</a></div>';return}let subtotal=cart.reduce((s,i)=>s+(PRODUCTS.find(p=>p.id===i.id).price*i.qty),0);el.innerHTML=`<div class="cart-layout"><div>${cart.map(i=>{let p=PRODUCTS.find(x=>x.id===i.id);return `<div class="cart-row"><img src="${p.image}" alt="${p.name}"><div><h3>${p.name}</h3><p>Size ${i.size} · ${money(p.price)}</p><div class="quantity"><button data-action="minus" data-id="${p.id}">−</button> ${i.qty} <button data-action="plus" data-id="${p.id}">+</button></div></div><strong>${money(p.price*i.qty)}</strong></div>`}).join('')}</div><aside class="summary"><h2>Order summary</h2><div><span>Subtotal</span><b>${money(subtotal)}</b></div><div><span>Delivery</span><b>Calculated at checkout</b></div><div class="total"><span>Total</span><b>${money(subtotal)}</b></div><button class="btn btn-primary" style="width:100%;justify-content:space-between" onclick="alert('Checkout integration requires a secure backend or payment provider.')">Proceed to checkout →</button></aside></div>`;el.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>{let c=getCart(),i=c.find(x=>x.id===b.dataset.id);b.dataset.action==='plus'?i.qty++:i.qty--;saveCart(c.filter(x=>x.qty>0));initCart()})}
document.addEventListener('DOMContentLoaded',()=>{updateCount();document.body.dataset.page==='home'&&initHome();document.body.dataset.page==='shop'&&initShop();document.body.dataset.page==='product'&&initProduct();document.body.dataset.page==='cart'&&initCart();document.querySelectorAll('.menu-toggle').forEach(b=>b.onclick=()=>document.querySelector('.main-nav').classList.toggle('show'))});
